# Generated by Django 5.1.15 on 2026-09-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disiplin", "0005_discipline_decision_e_school_processed_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplineappeal",
            name="previous_penalty_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REPRIMAND", "Kınama"),
                    ("SHORT_TERM_SUSPENSION", "Okuldan kısa süreli uzaklaştırma"),
                    ("SCHOOL_CHANGE", "Okul değiştirme"),
                    ("EXPULSION", "Örgün eğitim dışına çıkarma"),
                    ("NO_PENALTY", "Ceza verilmesine yer olmadığı"),
                ],
                default="",
                max_length=24,
                verbose_name="değişiklik öncesi ceza türü",
            ),
        ),
        migrations.AddField(
            model_name="disciplinedecision",
            name="penalty_removal_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Öğretmenler kurulu karar tarihi/sayısı vb. (md. 171/2).",
                verbose_name="ceza kaldırma açıklaması",
            ),
        ),
        migrations.AddField(
            model_name="disciplinedecision",
            name="penalty_removed_on",
            field=models.DateField(
                blank=True,
                help_text="Öğretmenler kurulunca cezanın kaldırılıp davranış puanının iade edildiği tarih; kaldırılan ceza puana, triaja ve EK-1 önceki cezalarına girmez (md. 171/3).",
                null=True,
                verbose_name="ceza kaldırma tarihi (md. 171/2)",
            ),
        ),
        migrations.AddField(
            model_name="disciplinedecision",
            name="referred_to_district",
            field=models.BooleanField(
                default=False,
                help_text="md. 197 ısrar-sevki yapıldıysa itiraz mercii bir üst kurula (il) kayar.",
                verbose_name="ilçe kuruluna gönderildi (md. 197)",
            ),
        ),
    ]
