# Generated by Django 5.1.15 on 2026-09-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disiplin", "0006_decision_legal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinedecision",
            name="md166_override_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Aynı öğretim yılında önceki cezadan ağır olmayan ceza verildiyse kurulun gerekçesi (md. 166 — kullanıcı kararı 26.09.2026). Evraka basılmaz.",
                verbose_name="md. 166 gerekçesi",
            ),
        ),
        migrations.AlterField(
            model_name="disciplineprecaution",
            name="requested_days",
            field=models.PositiveSmallIntegerField(
                help_text="md. 175/1: ilk karar en fazla 10 iş günü; md. 175/2 uzatmalarıyla toplam.",
                verbose_name="tedbir süresi (iş günü)",
            ),
        ),
    ]
