# Generated by Django 5.1.15 on 2026-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disiplin", "0007_decision_md166_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="honorcertificateevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Teklif edildi"),
                    ("RECOMMENDED", "Onur kurulu uygun gördü"),
                    ("AWARDED", "Ödül ve disiplin kurulu kabul etti"),
                    ("PRINCIPAL_APPROVED", "Okul müdürü onayladı"),
                    ("PRINCIPAL_REJECTED", "Okul müdürü onaylamadı"),
                    ("REJECTED", "Uygun görülmedi"),
                    ("UNDONE", "Son adım geri alındı"),
                ],
                max_length=20,
                verbose_name="işlem",
            ),
        ),
    ]
