# Generated by Django 5.1.15 on 2026-09-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disiplin", "0009_process_letters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateddocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("STATEMENT_CALL", "İfadeye çağrı pusulası (Form-3, md. 193)"),
                    ("STATEMENT_RECORD", "İfade tutanağı (Form-4/5/6, md. 193)"),
                    ("INFO_GATHERING", "Bilgi toplama formu (Form-7/8, md. 193)"),
                    ("DEFENSE_CALL", "Savunmaya çağrı (Form-9)"),
                    ("DEFENSE_RECORD", "Savunma tutanağı (Form-11)"),
                    ("MEETING_CALL", "Kurul toplantı çağrısı (Form-10, md. 190-191)"),
                    ("DEADLINE_EXTENSION", "Süre uzatma (Form-12/13, md. 192/3)"),
                    ("COMMITTEE_DECISION", "Kurul kararı (EK-1, md. 163-170)"),
                    ("INDEX_SHEET", "Dizi pusulası"),
                    ("PENALTY_NOTICE", "Ceza/Karar tebliği (Form-14/15, md. 169/5)"),
                    (
                        "PENALTY_DAYS_NOTICE",
                        "Ceza günleri tebliği (Form-16/17, md. 172)",
                    ),
                    ("APPEAL_LETTER", "İl/İlçe itiraz yazısı (Form-18, md. 169/3)"),
                    ("WARNING_LETTER", "Müdür uyarısı yazısı (Form-01/02, md. 157/7)"),
                    ("PRECAUTION_NOTICE", "Tedbir bildirimi (md. 175)"),
                    (
                        "COUNCIL_MEETING_MINUTES",
                        "Kurul toplantı tutanağı (md. 184/206)",
                    ),
                    ("BOARD_DECISION_NOTICE", "Üst kurul kararı tebliği (md. 169/2-4)"),
                    ("RETURN_LETTER", "Kurula iade yazısı (md. 197)"),
                    (
                        "DISTRICT_REFERRAL_LETTER",
                        "İlçe kuruluna gönderme yazısı (md. 197)",
                    ),
                    ("APPROVAL_REQUEST_LETTER", "Onaya sevk üst yazısı (md. 169/1)"),
                    ("PRECAUTION_MEM_LETTER", "Tedbir MEM yazısı (md. 175)"),
                    (
                        "PARENT_MEETING",
                        "Veli daveti / görüşme / gelmedi tutanağı (md. 157/7-b)",
                    ),
                    ("SEARCH_RECORD", "Arama tutanağı (md. 158/3)"),
                    (
                        "NON_COMPLIANCE_RECORD",
                        "İfade/savunma vermedi tespiti (md. 195)",
                    ),
                    ("OTHER", "Diğer"),
                ],
                max_length=32,
                verbose_name="belge türü",
            ),
        ),
    ]
