# Generated by Django 5.1.15 on 2026-10-04 20:52
#
# Kurul işleyişi Aşama 1 (04.10.2026): kurul kararı toplantının gündem maddesinde
# alınır (`CouncilAgendaItem`); onur belgesinin olumsuz sonucu kurula göre ikiye
# ayrılır (HONOR_BOARD_DECLINED / COMMITTEE_REJECTED).
#
# Veri göçü:
# 1. Eski `REJECTED` olayları, olay sırası (id) yeniden oynatılarak ayrılır: ret
#    anındaki son geçerli adım "uygun görüş" ise Ödül ve Disiplin Kurulu reddi,
#    değilse Onur Kurulunun uygun görmemesidir (UNDONE son adımı geri alır).
# 2. `REJECTED` durumundaki belge aynı ölçütle ayrılır (yeniden oynatma sonucu yoksa
#    `recommended_at` — `undo_honor_certificate_step` ile aynı ölçüt).
# 3. Geçerli kurul kararı olayı bir toplantıya bağlıysa (eski tarih eşleştirmesi),
#    o toplantıya karara bağlanmış gündem maddesi eklenir — karar defteri sürekliliği.
#    Toplantısız eski kararlar olduğu gibi kalır.
# Öğrenci adı okunmaz: parola kuruluysa açılışta (migrate anında) anahtar henüz yoktur.

import django.db.models.deletion
from django.db import migrations, models

_BOARD_DECISIONS = {"RECOMMENDED": "FAVORABLE", "DECLINED": "UNFAVORABLE"}
_COMMITTEE_DECISIONS = {"AWARDED": "FAVORABLE", "COMMITTEE_REJECTED": "UNFAVORABLE"}


def _split_and_backfill(apps, schema_editor):
    certificate_model = apps.get_model("disiplin", "HonorCertificate")
    event_model = apps.get_model("disiplin", "HonorCertificateEvent")
    agenda_model = apps.get_model("disiplin", "CouncilAgendaItem")

    for certificate in certificate_model.objects.all():
        steps: list = []  # geçerli adımlar (geri alınanlar düşülür)
        for event in event_model.objects.filter(certificate=certificate).order_by("id"):
            kind = event.event_type
            if kind == "PROPOSED":
                steps = []
                continue
            if kind == "UNDONE":
                if steps:
                    steps.pop()
                continue
            if kind == "REJECTED":
                after_recommendation = bool(steps) and steps[-1].event_type == "RECOMMENDED"
                kind = "COMMITTEE_REJECTED" if after_recommendation else "DECLINED"
                event.event_type = kind
                event.save(update_fields=["event_type"])
            steps.append(event)

        if certificate.status == "REJECTED":
            last = steps[-1].event_type if steps else ""
            if last == "COMMITTEE_REJECTED":
                certificate.status = "COMMITTEE_REJECTED"
            elif last == "DECLINED":
                certificate.status = "HONOR_BOARD_DECLINED"
            elif certificate.recommended_at is not None:
                certificate.status = "COMMITTEE_REJECTED"
            else:
                certificate.status = "HONOR_BOARD_DECLINED"
            certificate.save(update_fields=["status"])

        for event in steps:
            outcome = _BOARD_DECISIONS.get(event.event_type) or _COMMITTEE_DECISIONS.get(
                event.event_type
            )
            if outcome is None or event.meeting_id is None:
                continue
            if agenda_model.objects.filter(
                meeting_id=event.meeting_id, honor_certificate=certificate
            ).exists():
                continue
            order = agenda_model.objects.filter(meeting_id=event.meeting_id).count() + 1
            agenda_model.objects.create(
                meeting_id=event.meeting_id,
                order=order,
                item_type="HONOR_PROPOSAL",
                honor_certificate=certificate,
                outcome=outcome,
                decision_text=(
                    event.explanation or certificate.rejection_reason
                    if outcome == "UNFAVORABLE"
                    else ""
                ),
            )


class Migration(migrations.Migration):
    dependencies = [
        ("disiplin", "0011_guidance_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="honorcertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Teklif edildi"),
                    ("HONOR_BOARD_RECOMMENDED", "Onur kurulu uygun gördü"),
                    ("HONOR_BOARD_DECLINED", "Onur kurulu uygun görmedi"),
                    ("AWARDED", "Ödül ve disiplin kurulu kabul etti"),
                    ("COMMITTEE_REJECTED", "Ödül ve disiplin kurulu reddetti"),
                    ("PRINCIPAL_APPROVED", "Okul müdürü onayladı"),
                    ("PRINCIPAL_REJECTED", "Okul müdürü onaylamadı"),
                ],
                db_index=True,
                default="PROPOSED",
                max_length=24,
                verbose_name="durum",
            ),
        ),
        migrations.AlterField(
            model_name="honorcertificateevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Teklif edildi"),
                    ("RECOMMENDED", "Onur kurulu uygun gördü"),
                    ("DECLINED", "Onur kurulu uygun görmedi"),
                    ("AWARDED", "Ödül ve disiplin kurulu kabul etti"),
                    ("COMMITTEE_REJECTED", "Ödül ve disiplin kurulu reddetti"),
                    ("PRINCIPAL_APPROVED", "Okul müdürü onayladı"),
                    ("PRINCIPAL_REJECTED", "Okul müdürü onaylamadı"),
                    ("UNDONE", "Son adım geri alındı"),
                ],
                max_length=20,
                verbose_name="işlem",
            ),
        ),
        migrations.CreateModel(
            name="CouncilAgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="oluşturulma"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="güncellenme")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="silinme"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="sıra")),
                (
                    "item_type",
                    models.CharField(
                        choices=[("HONOR_PROPOSAL", "Onur belgesi teklifi")],
                        default="HONOR_PROPOSAL",
                        max_length=20,
                        verbose_name="madde türü",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Karar bekliyor"),
                            ("FAVORABLE", "Olumlu"),
                            ("UNFAVORABLE", "Olumsuz"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                        verbose_name="karar",
                    ),
                ),
                (
                    "decision_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "Olumsuz kararda zorunlu (md. 196/1, 206/2 — kararlar gerekçeli "
                            "yazılır)."
                        ),
                        verbose_name="karar gerekçesi",
                    ),
                ),
                (
                    "decision_basis",
                    models.CharField(
                        choices=[("UNANIMITY", "Oy birliği"), ("MAJORITY", "Oy çoğunluğu")],
                        default="UNANIMITY",
                        max_length=10,
                        verbose_name="karar esası",
                    ),
                ),
                (
                    "dissent_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Karara katılmayan üyenin adı ve gerekçesi (md. 196/2).",
                        verbose_name="karşı görüş",
                    ),
                ),
                (
                    "honor_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agenda_items",
                        to="disiplin.honorcertificate",
                        verbose_name="onur belgesi teklifi",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="disiplin.councilmeeting",
                        verbose_name="toplantı",
                    ),
                ),
            ],
            options={
                "verbose_name": "kurul gündem maddesi",
                "verbose_name_plural": "kurul gündem maddeleri",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(fields=["meeting", "order"], name="agenda_meeting_order_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True), ("outcome", "PENDING")),
                        fields=("honor_certificate",),
                        name="uq_agenda_certificate_pending_alive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("meeting", "honor_certificate"),
                        name="uq_agenda_meeting_certificate_alive",
                    ),
                ],
            },
        ),
        migrations.RunPython(_split_and_backfill, migrations.RunPython.noop),
    ]
