# Generated by Django 5.1.4 on 2026-07-23 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('first_name', models.CharField(max_length=100, verbose_name='ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='soyad')),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='unvan')),
                ('branch', models.CharField(blank=True, default='', max_length=64, verbose_name='branş')),
            ],
            options={
                'verbose_name': 'personel',
                'verbose_name_plural': 'personel',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('school_name', models.CharField(blank=True, default='', max_length=255, verbose_name='okul adı')),
                ('province', models.CharField(blank=True, default='', max_length=64, verbose_name='il')),
                ('district', models.CharField(blank=True, default='', max_length=64, verbose_name='ilçe')),
                ('principal_name', models.CharField(blank=True, default='', max_length=128, verbose_name='müdür adı')),
                ('setup_completed', models.BooleanField(default=False, verbose_name='kurulum tamamlandı')),
                ('app_password_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='uygulama parolası özeti')),
            ],
            options={
                'verbose_name': 'kurum yapılandırması',
                'verbose_name_plural': 'kurum yapılandırması',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=128, verbose_name='ad')),
                ('start_date', models.DateField(db_index=True, verbose_name='başlangıç')),
                ('end_date', models.DateField(verbose_name='bitiş')),
                ('kind', models.CharField(choices=[('OFFICIAL', 'Resmî tatil'), ('RELIGIOUS', 'Dini bayram'), ('OTHER', 'İdari/diğer')], default='OFFICIAL', max_length=16, verbose_name='tür')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='tahmini')),
            ],
            options={
                'verbose_name': 'tatil',
                'verbose_name_plural': 'tatiller',
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'start_date'), name='uq_holiday_name_start_alive')],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('source_type', models.CharField(choices=[('STUDENTS', 'Öğrenci-Veli'), ('PERSONNEL', 'Personel')], db_index=True, max_length=16, verbose_name='kaynak türü')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='dosya adı')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='içerik özeti (SHA256)')),
                ('status', models.CharField(choices=[('RUNNING', 'Çalışıyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Başarısız'), ('PREVIEWED', 'Önizlendi')], default='RUNNING', max_length=16, verbose_name='durum')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='bitiş')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='rapor')),
            ],
            options={
                'verbose_name': 'içe aktarma koşusu',
                'verbose_name_plural': 'içe aktarma koşuları',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source_type', 'file_hash'], name='okul_importrun_hash_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'COMPLETED')), fields=('source_type', 'file_hash'), name='uq_importrun_completed_per_hash')],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=32, verbose_name='ad')),
                ('start_date', models.DateField(verbose_name='başlangıç')),
                ('end_date', models.DateField(verbose_name='bitiş')),
                ('is_active', models.BooleanField(default=False, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'ders yılı',
                'verbose_name_plural': 'ders yılları',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_schoolyear_name_alive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('is_active',), name='uq_schoolyear_single_active')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('tckn', models.CharField(blank=True, default='', max_length=11, verbose_name='TCKN')),
                ('first_name', models.CharField(max_length=100, verbose_name='ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='soyad')),
                ('student_number', models.CharField(blank=True, default='', max_length=16, verbose_name='okul no')),
                ('class_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='sınıf')),
                ('class_section', models.CharField(blank=True, default='', max_length=8, verbose_name='şube')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='doğum tarihi')),
                ('gender', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kız')], default='', max_length=1, verbose_name='cinsiyet')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('LEFT', 'Ayrıldı')], default='ACTIVE', max_length=16, verbose_name='durum')),
                ('guardian_name', models.CharField(blank=True, default='', max_length=200, verbose_name='veli adı')),
                ('guardian_kinship', models.CharField(blank=True, choices=[('ANNE', 'Anne'), ('BABA', 'Baba'), ('DIGER', 'Diğer')], default='', max_length=8, verbose_name='veli yakınlığı')),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=16, verbose_name='veli telefonu')),
                ('guardian_phone2', models.CharField(blank=True, default='', max_length=16, verbose_name='ikinci veli telefonu')),
                ('guardian_address', models.TextField(blank=True, default='', verbose_name='veli adresi')),
            ],
            options={
                'verbose_name': 'öğrenci',
                'verbose_name_plural': 'öğrenciler',
                'ordering': ['class_level', 'class_section', 'student_number'],
                'indexes': [models.Index(fields=['class_level', 'class_section'], name='okul_student_class_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('tckn', ''), _negated=True)), fields=('tckn',), name='uq_student_tckn_alive')],
            },
        ),
    ]
