# Generated by Django 5.1.4 on 2026-07-24 08:34

import shared.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_address',
            field=shared.crypto.EncryptedTextField(blank=True, default='', verbose_name='veli adresi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=shared.crypto.EncryptedCharField(blank=True, default='', max_length=200, verbose_name='veli adı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=shared.crypto.EncryptedCharField(blank=True, default='', max_length=16, verbose_name='veli telefonu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone2',
            field=shared.crypto.EncryptedCharField(blank=True, default='', max_length=16, verbose_name='ikinci veli telefonu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tckn',
            field=shared.crypto.EncryptedCharField(blank=True, default='', max_length=11, verbose_name='TCKN'),
        ),
    ]
