# Generated by Django 5.1.15 on 2026-09-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0004_schoolterm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OFFICIAL", "Resmî tatil"),
                    ("RELIGIOUS", "Dini bayram"),
                    ("OTHER", "İdari/diğer"),
                    ("SCHOOL_BREAK", "Ara tatil (okul kapalı, iş günü sürer)"),
                ],
                default="OFFICIAL",
                max_length=16,
                verbose_name="tür",
            ),
        ),
    ]
