# Generated by Django 5.1.15 on 2026-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0005_holiday_school_break"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Aktif"),
                    ("LEFT", "Ayrıldı"),
                    ("GRADUATED", "Mezun"),
                ],
                default="ACTIVE",
                max_length=16,
                verbose_name="durum",
            ),
        ),
    ]
